"""Generate the frontend page manifest and Vite-compatible entry files.

The Python route table is the single source of truth. This module generates
deterministic files in `.catba/generated/` that Vite processes:

- manifest.json: maps page IDs to page module paths
- ssr-entry.js: imports all page modules, exports render(pageId, props)
- client-entry.js: imports all page modules, hydrates the server-rendered DOM

No routing logic lives in the generated JavaScript. The manifest maps page
identifiers to components; the Python route table decides which page matches.
"""

import json
import os

from catba.pages import PageModule


def generate_manifest(pages, output_dir):
    """Write the page manifest as manifest.json in output_dir.

    Returns the path to the manifest file.
    """
    os.makedirs(output_dir, exist_ok=True)
    manifest = {p.page_id: p.module_path for p in pages}
    path = os.path.join(output_dir, "manifest.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2, sort_keys=True)
        f.write("\n")
    return path


def _generate_layout_code(pages):
    """Generate layout imports and hierarchical Page.layout wiring lines."""
    unique_layouts = []
    layout_indices = {}
    for p in pages:
        for lp in getattr(p, "layout_paths", []):
            if lp not in layout_indices:
                layout_indices[lp] = len(unique_layouts)
                unique_layouts.append(lp)

    import_lines = []
    for lp, idx in layout_indices.items():
        rel = _relative_import(lp)
        import_lines.append(f'import Layout{idx} from "{rel}"')

    wire_lines = []
    for i, p in enumerate(pages):
        lps = getattr(p, "layout_paths", [])
        if not lps:
            continue
        expr = "page"
        for lp in reversed(lps):
            idx = layout_indices[lp]
            expr = f"createElement(Layout{idx}, null, {expr})"
        wire_lines.append(f"if (typeof Page{i}.layout === \"undefined\") {{")
        wire_lines.append(f"  Page{i}.layout = (page) => {expr}")
        wire_lines.append("}")

    return import_lines, wire_lines


def generate_ssr_entry(pages, output_dir, use_inertia=False):
    """Write the Vite SSR entry file.

    When use_inertia is True, sets up createInertiaApp on the server for
    React and Inertia features (like Head, Layouts, etc.).
    When use_inertia is False, exports a render(pageId, props) function that
    calls React's renderToString.

    Returns the path to the entry file.
    """
    os.makedirs(output_dir, exist_ok=True)
    layout_imports, layout_wires = _generate_layout_code(pages)

    if use_inertia:
        lines = [
            "// Generated by CatBa. Do not edit.",
            "// This file imports all page modules and exports render(pageId, props, options).",
            'import { createInertiaApp } from "@inertiajs/react"',
            'import { renderToString } from "react-dom/server"',
            'import { createElement } from "react"',
            "",
        ]
        for i, p in enumerate(pages):
            rel = _relative_import(p.module_path)
            lines.append(f'import Page{i} from "{rel}"')

        if layout_imports:
            lines.append("")
            lines.extend(layout_imports)

        if layout_wires:
            lines.append("")
            lines.extend(layout_wires)

        lines.append("")
        lines.append("const pages = {")
        for i, p in enumerate(pages):
            lines.append(f'  {json.dumps(p.page_id)}: Page{i},')
        lines.append("}")
        lines.append("")
        lines.append("export async function render(pageId, props, options = {}) {")
        lines.append("  const Component = pages[pageId]")
        lines.append("  if (!Component) {")
        lines.append('    throw new Error("Unknown page: " + pageId)')
        lines.append("  }")
        lines.append("  const result = await createInertiaApp({")
        lines.append('    id: "catba-root",')
        lines.append("    page: {")
        lines.append("      component: pageId,")
        lines.append("      props: props,")
        lines.append('      url: (options && options.url) || pageId,')
        lines.append('      version: (options && options.version) || "dev",')
        lines.append("    },")
        lines.append("    render: renderToString,")
        lines.append("    resolve: (name) => pages[name],")
        lines.append("    setup: ({ App, props }) => createElement(App, props),")
        lines.append("  })")
        lines.append("  return result")
        lines.append("}")
        lines.append("")
    else:
        lines = [
            "// Generated by CatBa. Do not edit.",
            "// This file imports all page modules and exports render(pageId, props).",
            'import { renderToString } from "react-dom/server"',
            'import { createElement } from "react"',
            "",
        ]

        # Import each page module.
        for i, p in enumerate(pages):
            rel = _relative_import(p.module_path)
            lines.append(f'import Page{i} from "{rel}"')

        if layout_imports:
            lines.append("")
            lines.extend(layout_imports)

        if layout_wires:
            lines.append("")
            lines.extend(layout_wires)

        lines.append("")
        lines.append("const pages = {")
        for i, p in enumerate(pages):
            lines.append(f'  {json.dumps(p.page_id)}: Page{i},')
        lines.append("}")
        lines.append("")
        lines.append("export function render(pageId, props) {")
        lines.append("  const Component = pages[pageId]")
        lines.append("  if (!Component) {")
        lines.append('    throw new Error("Unknown page: " + pageId)')
        lines.append("  }")
        lines.append("  const page = createElement(Component, props)")
        lines.append('  if (typeof Component.layout === "function") {')
        lines.append("    return renderToString(Component.layout(page))")
        lines.append("  }")
        lines.append("  return renderToString(page)")
        lines.append("}")
        lines.append("")

    path = os.path.join(output_dir, "ssr-entry.js")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    return path


def generate_client_entry(pages, output_dir, use_inertia=False):
    """Write the Vite client entry file.

    When use_inertia is True, sets up the official @inertiajs/react app.
    When use_inertia is False, reads page ID + serialized props from the DOM
    and directly hydrates the server-rendered root element.

    Returns the path to the entry file.
    """
    os.makedirs(output_dir, exist_ok=True)
    layout_imports, layout_wires = _generate_layout_code(pages)

    if use_inertia:
        lines = [
            "// Generated by CatBa. Do not edit.",
            "// This file initializes the Inertia client app with React.",
            'import { createInertiaApp } from "@inertiajs/react"',
            'import { hydrateRoot } from "react-dom/client"',
            'import { createElement } from "react"',
            "",
        ]
        for i, p in enumerate(pages):
            rel = _relative_import(p.module_path)
            lines.append(f'import Page{i} from "{rel}"')

        if layout_imports:
            lines.append("")
            lines.extend(layout_imports)

        if layout_wires:
            lines.append("")
            lines.extend(layout_wires)

        lines.append("")
        lines.append("const pages = {")
        for i, p in enumerate(pages):
            lines.append(f'  {json.dumps(p.page_id)}: Page{i},')
        lines.append("}")
        lines.append("")
        lines.append("createInertiaApp({")
        lines.append('  id: "catba-root",')
        lines.append("  resolve: (name) => pages[name],")
        lines.append("  setup({ el, App, props }) {")
        lines.append("    hydrateRoot(el, createElement(App, props))")
        lines.append("  },")
        lines.append("})")
        lines.append("")
    else:
        lines = [
            "// Generated by CatBa. Do not edit.",
            "// This file reads page ID + props from the DOM and hydrates.",
            'import { hydrateRoot } from "react-dom/client"',
            'import { createElement } from "react"',
            "",
        ]

        # Import each page module.
        for i, p in enumerate(pages):
            rel = _relative_import(p.module_path)
            lines.append(f'import Page{i} from "{rel}"')

        if layout_imports:
            lines.append("")
            lines.extend(layout_imports)

        if layout_wires:
            lines.append("")
            lines.extend(layout_wires)

        lines.append("")
        lines.append("const pages = {")
        for i, p in enumerate(pages):
            lines.append(f'  {json.dumps(p.page_id)}: Page{i},')
        lines.append("}")
        lines.append("")
        lines.append("const root = document.getElementById(\"catba-root\")")
        lines.append("if (root) {")
        lines.append("  const state = root.getAttribute(\"data-catba-page\")")
        lines.append("  const propsScript = document.getElementById(\"catba-props\")")
        lines.append("  let pageId = null")
        lines.append("  let props = {}")
        lines.append("  if (state) {")
        lines.append("    pageId = state")
        lines.append("  }")
        lines.append("  if (propsScript && propsScript.textContent) {")
        lines.append("    try { props = JSON.parse(propsScript.textContent) } catch (e) {}")
        lines.append("  }")
        lines.append("  const Component = pages[pageId]")
        lines.append("  if (Component) {")
        lines.append("    const el = typeof Component.layout === \"function\"")
        lines.append("      ? Component.layout(createElement(Component, props))")
        lines.append("      : createElement(Component, props)")
        lines.append("    hydrateRoot(root, el)")
        lines.append("  }")
        lines.append("}")
        lines.append("")

    path = os.path.join(output_dir, "client-entry.js")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    return path


def _relative_import(module_path):
    """Convert a project-relative module path to a path relative to .catba/generated/.

    .catba/generated/ is two levels below the project root, so a path like
    "app/page.tsx" becomes "../../app/page.tsx".
    """
    return "../../" + module_path
