"""Generate the frontend page manifest and Vite-compatible entry files.

The Python route table is the single source of truth. This module generates
deterministic files in `.catba/generated/` that Vite processes:

- manifest.json: maps page IDs to page module paths
- ssr-entry.js: imports all page modules, exports render(pageId, props)
- client-entry.js: imports all page modules, hydrates the server-rendered DOM

No routing logic lives in the generated JavaScript. The manifest maps page
identifiers to components; the Python route table decides which page matches.
"""

import json
import os

from catba.pages import PageModule


def generate_manifest(pages, output_dir):
    """Write the page manifest as manifest.json in output_dir.

    Returns the path to the manifest file.
    """
    os.makedirs(output_dir, exist_ok=True)
    manifest = {p.page_id: p.module_path for p in pages}
    path = os.path.join(output_dir, "manifest.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2, sort_keys=True)
        f.write("\n")
    return path


def generate_ssr_entry(pages, output_dir):
    """Write the Vite SSR entry file.

    The entry imports all page modules and exports a render(pageId, props)
    function that returns an HTML string via React's renderToString.

    Returns the path to the entry file.
    """
    os.makedirs(output_dir, exist_ok=True)

    lines = [
        "// Generated by CatBa. Do not edit.",
        "// This file imports all page modules and exports render(pageId, props).",
        'import { renderToString } from "react-dom/server"',
        'import { createElement } from "react"',
        "",
    ]

    # Import each page module.
    for i, p in enumerate(pages):
        # Relative path from .catba/generated/ to the project root.
        rel = _relative_import(p.module_path)
        lines.append(f'import Page{i} from "{rel}"')

    lines.append("")
    lines.append("const pages = {")
    for i, p in enumerate(pages):
        lines.append(f'  {json.dumps(p.page_id)}: Page{i},')
    lines.append("}")
    lines.append("")
    lines.append("export function render(pageId, props) {")
    lines.append("  const Component = pages[pageId]")
    lines.append("  if (!Component) {")
    lines.append('    throw new Error("Unknown page: " + pageId)')
    lines.append("  }")
    lines.append("  return renderToString(createElement(Component, props))")
    lines.append("}")
    lines.append("")

    path = os.path.join(output_dir, "ssr-entry.js")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    return path


def generate_client_entry(pages, output_dir):
    """Write the Vite client entry file.

    The entry reads the page ID and serialized props from the DOM and
    hydrates the server-rendered root element.

    Returns the path to the entry file.
    """
    os.makedirs(output_dir, exist_ok=True)

    lines = [
        "// Generated by CatBa. Do not edit.",
        "// This file reads page ID + props from the DOM and hydrates.",
        'import { hydrateRoot } from "react-dom/client"',
        'import { createElement } from "react"',
        "",
    ]

    # Import each page module.
    for i, p in enumerate(pages):
        rel = _relative_import(p.module_path)
        lines.append(f'import Page{i} from "{rel}"')

    lines.append("")
    lines.append("const pages = {")
    for i, p in enumerate(pages):
        lines.append(f'  {json.dumps(p.page_id)}: Page{i},')
    lines.append("}")
    lines.append("")
    lines.append("const root = document.getElementById(\"catba-root\")")
    lines.append("if (root) {")
    lines.append("  const state = root.getAttribute(\"data-catba-page\")")
    lines.append("  const propsScript = document.getElementById(\"catba-props\")")
    lines.append("  let pageId = null")
    lines.append("  let props = {}")
    lines.append("  if (state) {")
    lines.append("    pageId = state")
    lines.append("  }")
    lines.append("  if (propsScript && propsScript.textContent) {")
    lines.append("    try { props = JSON.parse(propsScript.textContent) } catch (e) {}")
    lines.append("  }")
    lines.append("  const Component = pages[pageId]")
    lines.append("  if (Component) {")
    lines.append("    hydrateRoot(root, createElement(Component, props))")
    lines.append("  }")
    lines.append("}")
    lines.append("")

    path = os.path.join(output_dir, "client-entry.js")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    return path


def _relative_import(module_path):
    """Convert a project-relative module path to a path relative to .catba/generated/.

    .catba/generated/ is two levels below the project root, so a path like
    "app/page.tsx" becomes "../../app/page.tsx".
    """
    return "../../" + module_path
